# Plugins
gems:             [jekyll-paginate, jekyll-gist]

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cheatsheets
tagline:          Code cheatsheets collection
description:      "\"The only difference between science and screwing around is writing it down\""
url:              http://karloespiritu.com/cheatsheets/
baseurl:          "/cheatsheets/" # change to "/cheatsheets/" or whatever URL subdirectory in actual website

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/karloespiritu/cheatsheets
